## Exploración datos PIB

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import pathlib
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
root = 'Data PIB 1993.xlsx'

df_pib = pd.read_excel(root)
df_pib.head()

,Country Name,Country Code,Series Name,Series Code,1993 [YR1993],1994 [YR1994],1995 [YR1995],1996 [YR1996],1997 [YR1997],1998 [YR1998],...,2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020]
0,Argentina,ARG,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,8.206979,5.836201,-2.845210,5.526690,8.111047,3.850179,...,6.003952,-1.026420,2.405324,-2.512615,2.73116,-2.08033,2.8185,-2.56535,-2.08801,..
1,Belice,BLZ,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,6.275692,0.131231,0.656349,1.416841,3.579933,3.724423,...,1.922035,2.413483,1.302125,3.635360,2.84964,0.0850812,1.8702,2.07895,0.27368,..
2,Bolivia,BOL,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,4.269294,4.667270,4.678273,4.361343,4.954209,5.029352,...,5.204092,5.122276,6.796011,5.460570,4.85719,4.26392,4.19521,4.22362,2.21671,..
3,Brasil,BRA,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,4.665169,5.334552,4.416731,2.207536,3.394846,0.338098,...,3.974425,1.921150,3.004846,0.503956,-3.54576,-3.27592,1.32287,1.31722,1.13659,..
4,Chile,CHL,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,6.588784,5.030198,8.933296,6.802917,7.427890,4.324579,...,6.110919,5.318628,4.045004,1.766740,2.30377,1.71109,1.18857,3.94932,1.05444,..

In [4]:
df_pib.tail(15)

,Country Name,Country Code,Series Name,Series Code,1993 [YR1993],1994 [YR1994],1995 [YR1995],1996 [YR1996],1997 [YR1997],1998 [YR1998],...,2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020]
9,El Salvador,SLV,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,5.819235,4.689784,4.734960,0.817680,3.134940,2.654174,...,3.815356,2.814390,2.235730,1.711223,2.39503,2.54653,2.24994,2.43096,2.38236,..
10,Guatemala,GTM,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,3.927132,4.033741,4.948548,2.957780,4.364090,4.993528,...,4.162049,2.969857,3.697586,4.443978,4.09217,2.6778,3.02343,3.21491,3.8449,..
11,España,ESP,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,-1.031492,2.383195,2.757494,2.660524,3.702580,4.393037,...,-0.814373,-2.959441,-1.435394,1.383908,3.83517,3.0313,2.97364,2.43005,1.95013,..
12,Guyana,GUY,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,8.175105,8.532423,5.031447,7.955518,6.180666,-1.679104,...,5.196298,5.276320,3.653408,1.686400,0.687398,3.80748,3.73449,4.44098,5.35283,..
13,Haití,HTI,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,-5.426296,-11.950629,9.897707,4.140773,2.704714,2.181840,...,6.154225,0.553167,3.085009,3.401777,1.61692,1.72254,2.28613,1.66783,-1.68199,..
14,Honduras,HND,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,6.495718,0.211903,6.189305,1.870776,4.598083,3.590233,...,3.835691,4.128688,2.791560,3.058081,3.84008,3.89297,4.84291,3.69673,2.65276,..
15,México,MEX,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,1.941156,4.941081,-6.291231,6.773259,6.846852,5.163925,...,3.663008,3.642323,1.354092,2.849773,3.29315,2.63053,2.11313,2.19499,-0.0545279,..
16,Nicaragua,NIC,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,-0.392936,3.337726,5.911908,6.344268,3.966651,3.711681,...,6.316710,6.496747,4.926115,4.786492,4.79206,4.56293,4.63082,-3.94986,-3.87905,..
17,Panamá,PAN,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,5.455744,2.850147,1.751679,4.079703,6.460990,7.341501,...,11.313732,9.778904,6.903273,5.066743,5.73276,4.9535,5.59901,3.6921,3.00639,..
18,Paraguay,PRY,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,4.936359,5.317918,6.822810,1.573785,4.242516,0.068038,...,4.249111,-0.538513,8.417495,4.860890,3.08037,4.3129,4.95377,3.35617,-0.0299144,..
19,Perú,PER,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,5.243577,12.308366,7.411395,2.798973,6.476824,-0.391538,...,6.327192,6.139725,5.852518,2.382157,3.25224,3.95332,2.51884,3.97694,2.15013,..
20,República Dominicana,DOM,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,7.364513,2.600354,5.685431,5.977825,8.885269,6.714478,...,3.133423,2.717368,4.875205,7.050464,6.92702,6.6592,4.6667,6.98253,5.05217,..
21,Suriname,SUR,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,-6.699998,3.400000,0.000000,1.000000,5.699999,2.300001,...,5.849368,2.690350,2.933441,0.255503,-3.4111,-5.56119,1.7623,2.57656,0.267655,..
22,Uruguay,URY,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,2.657546,7.281343,-1.447599,5.577958,8.547683,4.518890,...,5.162133,3.538179,4.637539,3.238791,0.370741,1.6898,2.59134,1.62008,0.222122,..
23,Venezuela,VEN,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,0.275388,-2.349508,3.951663,-0.197837,6.370931,0.294055,...,4.176425,5.625957,1.343094,-3.894386,..,..,..,..,..,..

In [5]:
df_pib.dropna()

,Country Name,Country Code,Series Name,Series Code,1993 [YR1993],1994 [YR1994],1995 [YR1995],1996 [YR1996],1997 [YR1997],1998 [YR1998],...,2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020]
0,Argentina,ARG,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,8.206979,5.836201,-2.845210,5.526690,8.111047,3.850179,...,6.003952,-1.026420,2.405324,-2.512615,2.73116,-2.08033,2.8185,-2.56535,-2.08801,..
1,Belice,BLZ,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,6.275692,0.131231,0.656349,1.416841,3.579933,3.724423,...,1.922035,2.413483,1.302125,3.635360,2.84964,0.0850812,1.8702,2.07895,0.27368,..
2,Bolivia,BOL,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,4.269294,4.667270,4.678273,4.361343,4.954209,5.029352,...,5.204092,5.122276,6.796011,5.460570,4.85719,4.26392,4.19521,4.22362,2.21671,..
3,Brasil,BRA,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,4.665169,5.334552,4.416731,2.207536,3.394846,0.338098,...,3.974425,1.921150,3.004846,0.503956,-3.54576,-3.27592,1.32287,1.31722,1.13659,..
4,Chile,CHL,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,6.588784,5.030198,8.933296,6.802917,7.427890,4.324579,...,6.110919,5.318628,4.045004,1.766740,2.30377,1.71109,1.18857,3.94932,1.05444,..
5,Colombia,COL,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,5.385410,5.814662,5.202438,2.055855,3.430294,0.569784,...,6.947892,3.912636,5.133994,4.499030,2.9559,2.08738,1.35936,2.51532,3.26022,..
6,Costa Rica,CRI,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,7.087517,4.487267,4.121496,1.237816,5.564946,6.961700,...,4.307102,4.796920,2.269027,3.515339,3.63173,4.24599,3.8602,2.66038,2.08379,..
7,Cuba,CUB,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,-14.878181,0.716930,2.457201,7.838750,2.783425,0.159146,...,2.802301,3.014900,2.747603,1.047577,4.43814,0.513761,1.80905,2.24848,..,..
8,Ecuador,ECU,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,1.973218,4.258250,2.252549,1.731748,4.327865,3.266529,...,7.868141,5.641962,4.946511,3.788869,0.0988726,-1.22638,2.36839,1.28929,0.0537188,..
9,El Salvador,SLV,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,5.819235,4.689784,4.734960,0.817680,3.134940,2.654174,...,3.815356,2.814390,2.235730,1.711223,2.39503,2.54653,2.24994,2.43096,2.38236,..
10,Guatemala,GTM,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,3.927132,4.033741,4.948548,2.957780,4.364090,4.993528,...,4.162049,2.969857,3.697586,4.443978,4.09217,2.6778,3.02343,3.21491,3.8449,..
11,España,ESP,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,-1.031492,2.383195,2.757494,2.660524,3.702580,4.393037,...,-0.814373,-2.959441,-1.435394,1.383908,3.83517,3.0313,2.97364,2.43005,1.95013,..
12,Guyana,GUY,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,8.175105,8.532423,5.031447,7.955518,6.180666,-1.679104,...,5.196298,5.276320,3.653408,1.686400,0.687398,3.80748,3.73449,4.44098,5.35283,..
13,Haití,HTI,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,-5.426296,-11.950629,9.897707,4.140773,2.704714,2.181840,...,6.154225,0.553167,3.085009,3.401777,1.61692,1.72254,2.28613,1.66783,-1.68199,..
14,Honduras,HND,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,6.495718,0.211903,6.189305,1.870776,4.598083,3.590233,...,3.835691,4.128688,2.791560,3.058081,3.84008,3.89297,4.84291,3.69673,2.65276,..
15,México,MEX,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,1.941156,4.941081,-6.291231,6.773259,6.846852,5.163925,...,3.663008,3.642323,1.354092,2.849773,3.29315,2.63053,2.11313,2.19499,-0.0545279,..
16,Nicaragua,NIC,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,-0.392936,3.337726,5.911908,6.344268,3.966651,3.711681,...,6.316710,6.496747,4.926115,4.786492,4.79206,4.56293,4.63082,-3.94986,-3.87905,..
17,Panamá,PAN,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,5.455744,2.850147,1.751679,4.079703,6.460990,7.341501,...,11.313732,9.778904,6.903273,5.066743,5.73276,4.9535,5.59901,3.6921,3.00639,..
18,Paraguay,PRY,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,4.936359,5.317918,6.822810,1.573785,4.242516,0.068038,...,4.249111,-0.538513,8.417495,4.860890,3.08037,4.3129,4.95377,3.35617,-0.0299144,..
19,Perú,PER,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,5.243577,12.308366,7.411395,2.798973,6.476824,-0.391538,...,6.327192,6.139725,5.852518,2.382157,3.25224,3.95332,2.51884,3.97694,2.15013,..
20,República Dominicana,DOM,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,7.364513,2.600354,5.685431,5.977825,8.885269,6.714478,...,3.133423,2.717368,4.875205,7.050464,6.92702,6.6592,4.6667,6.98253,5.05217,..
21,Suriname,SUR,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,-6.699998,3.400000,0.000000,1.000000,5.699999,2.300001,...,5.849368,2.690350,2.933441,0.255503,-3.4111,-5.56119,1.7623,2.57656,0.267655,..
22,Uruguay,URY,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,2.657546,7.281343,-1.447599,5.577958,8.547683,4.518890,...,5.162133,3.538179,4.637539,3.238791,0.370741,1.6898,2.59134,1.62008,0.222122,..
23,Venezuela,VEN,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,0.275388,-2.349508,3.951663,-0.197837,6.370931,0.294055,...,4.176425,5.625957,1.343094,-3.894386,..,..,..,..,..,..

In [6]:
df_pib.tail(15)

,Country Name,Country Code,Series Name,Series Code,1993 [YR1993],1994 [YR1994],1995 [YR1995],1996 [YR1996],1997 [YR1997],1998 [YR1998],...,2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020]
14,Honduras,HND,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,6.495718,0.211903,6.189305,1.870776,4.598083,3.590233,...,3.835691,4.128688,2.791560,3.058081,3.84008,3.89297,4.84291,3.69673,2.65276,..
15,México,MEX,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,1.941156,4.941081,-6.291231,6.773259,6.846852,5.163925,...,3.663008,3.642323,1.354092,2.849773,3.29315,2.63053,2.11313,2.19499,-0.0545279,..
16,Nicaragua,NIC,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,-0.392936,3.337726,5.911908,6.344268,3.966651,3.711681,...,6.316710,6.496747,4.926115,4.786492,4.79206,4.56293,4.63082,-3.94986,-3.87905,..
17,Panamá,PAN,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,5.455744,2.850147,1.751679,4.079703,6.460990,7.341501,...,11.313732,9.778904,6.903273,5.066743,5.73276,4.9535,5.59901,3.6921,3.00639,..
18,Paraguay,PRY,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,4.936359,5.317918,6.822810,1.573785,4.242516,0.068038,...,4.249111,-0.538513,8.417495,4.860890,3.08037,4.3129,4.95377,3.35617,-0.0299144,..
19,Perú,PER,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,5.243577,12.308366,7.411395,2.798973,6.476824,-0.391538,...,6.327192,6.139725,5.852518,2.382157,3.25224,3.95332,2.51884,3.97694,2.15013,..
20,República Dominicana,DOM,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,7.364513,2.600354,5.685431,5.977825,8.885269,6.714478,...,3.133423,2.717368,4.875205,7.050464,6.92702,6.6592,4.6667,6.98253,5.05217,..
21,Suriname,SUR,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,-6.699998,3.400000,0.000000,1.000000,5.699999,2.300001,...,5.849368,2.690350,2.933441,0.255503,-3.4111,-5.56119,1.7623,2.57656,0.267655,..
22,Uruguay,URY,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,2.657546,7.281343,-1.447599,5.577958,8.547683,4.518890,...,5.162133,3.538179,4.637539,3.238791,0.370741,1.6898,2.59134,1.62008,0.222122,..
23,Venezuela,VEN,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,0.275388,-2.349508,3.951663,-0.197837,6.370931,0.294055,...,4.176425,5.625957,1.343094,-3.894386,..,..,..,..,..,..
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Data from Database: Indicadores del desarrollo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Last Updated: 03/19/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df_pib.columns

Index(['Country Name', 'Country Code', 'Series Name', 'Series Code',
       '1993 [YR1993]', '1994 [YR1994]', '1995 [YR1995]', '1996 [YR1996]',
       '1997 [YR1997]', '1998 [YR1998]', '1999 [YR1999]', '2000 [YR2000]',
       '2001 [YR2001]', '2002 [YR2002]', '2003 [YR2003]', '2004 [YR2004]',
       '2005 [YR2005]', '2006 [YR2006]', '2007 [YR2007]', '2008 [YR2008]',
       '2009 [YR2009]', '2010 [YR2010]', '2011 [YR2011]', '2012 [YR2012]',
       '2013 [YR2013]', '2014 [YR2014]', '2015 [YR2015]', '2016 [YR2016]',
       '2017 [YR2017]', '2018 [YR2018]', '2019 [YR2019]', '2020 [YR2020]'],
      dtype='object')

In [4]:
df_pib = df_pib.drop(['Series Name','Series Code'], axis=1)
df_pib.head()

,Country Name,Country Code,1993 [YR1993],1994 [YR1994],1995 [YR1995],1996 [YR1996],1997 [YR1997],1998 [YR1998],1999 [YR1999],2000 [YR2000],...,2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020]
0,Argentina,ARG,8.206979,5.836201,-2.845210,5.526690,8.111047,3.850179,-3.385457,-0.788999,...,6.003952,-1.026420,2.405324,-2.512615,2.73116,-2.08033,2.8185,-2.56535,-2.08801,..
1,Belice,BLZ,6.275692,0.131231,0.656349,1.416841,3.579933,3.724423,8.784632,13.019560,...,1.922035,2.413483,1.302125,3.635360,2.84964,0.0850812,1.8702,2.07895,0.27368,..
2,Bolivia,BOL,4.269294,4.667270,4.678273,4.361343,4.954209,5.029352,0.426890,2.507808,...,5.204092,5.122276,6.796011,5.460570,4.85719,4.26392,4.19521,4.22362,2.21671,..
3,Brasil,BRA,4.665169,5.334552,4.416731,2.207536,3.394846,0.338098,0.467938,4.387949,...,3.974425,1.921150,3.004846,0.503956,-3.54576,-3.27592,1.32287,1.31722,1.13659,..
4,Chile,CHL,6.588784,5.030198,8.933296,6.802917,7.427890,4.324579,-0.412096,5.326938,...,6.110919,5.318628,4.045004,1.766740,2.30377,1.71109,1.18857,3.94932,1.05444,..

In [5]:
df_pib.columns = ['Country Name', 'Country Code', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020']

In [6]:
df_pib.head()

,Country Name,Country Code,1993,1994,1995,1996,1997,1998,1999,2000,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Argentina,ARG,8.206979,5.836201,-2.845210,5.526690,8.111047,3.850179,-3.385457,-0.788999,...,6.003952,-1.026420,2.405324,-2.512615,2.73116,-2.08033,2.8185,-2.56535,-2.08801,..
1,Belice,BLZ,6.275692,0.131231,0.656349,1.416841,3.579933,3.724423,8.784632,13.019560,...,1.922035,2.413483,1.302125,3.635360,2.84964,0.0850812,1.8702,2.07895,0.27368,..
2,Bolivia,BOL,4.269294,4.667270,4.678273,4.361343,4.954209,5.029352,0.426890,2.507808,...,5.204092,5.122276,6.796011,5.460570,4.85719,4.26392,4.19521,4.22362,2.21671,..
3,Brasil,BRA,4.665169,5.334552,4.416731,2.207536,3.394846,0.338098,0.467938,4.387949,...,3.974425,1.921150,3.004846,0.503956,-3.54576,-3.27592,1.32287,1.31722,1.13659,..
4,Chile,CHL,6.588784,5.030198,8.933296,6.802917,7.427890,4.324579,-0.412096,5.326938,...,6.110919,5.318628,4.045004,1.766740,2.30377,1.71109,1.18857,3.94932,1.05444,..

In [7]:
df_pib.dtypes

Country Name     object
Country Code     object
1993            float64
1994            float64
1995            float64
1996            float64
1997            float64
1998            float64
1999            float64
2000            float64
2001            float64
2002            float64
2003            float64
2004            float64
2005            float64
2006            float64
2007            float64
2008            float64
2009            float64
2010            float64
2011            float64
2012            float64
2013            float64
2014            float64
2015             object
2016             object
2017             object
2018             object
2019             object
2020             object
dtype: object

In [8]:
df_pib['Country Name'] = df_pib['Country Name'].str.upper()
df_pib.head()

,Country Name,Country Code,1993,1994,1995,1996,1997,1998,1999,2000,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,ARGENTINA,ARG,8.206979,5.836201,-2.845210,5.526690,8.111047,3.850179,-3.385457,-0.788999,...,6.003952,-1.026420,2.405324,-2.512615,2.73116,-2.08033,2.8185,-2.56535,-2.08801,..
1,BELICE,BLZ,6.275692,0.131231,0.656349,1.416841,3.579933,3.724423,8.784632,13.019560,...,1.922035,2.413483,1.302125,3.635360,2.84964,0.0850812,1.8702,2.07895,0.27368,..
2,BOLIVIA,BOL,4.269294,4.667270,4.678273,4.361343,4.954209,5.029352,0.426890,2.507808,...,5.204092,5.122276,6.796011,5.460570,4.85719,4.26392,4.19521,4.22362,2.21671,..
3,BRASIL,BRA,4.665169,5.334552,4.416731,2.207536,3.394846,0.338098,0.467938,4.387949,...,3.974425,1.921150,3.004846,0.503956,-3.54576,-3.27592,1.32287,1.31722,1.13659,..
4,CHILE,CHL,6.588784,5.030198,8.933296,6.802917,7.427890,4.324579,-0.412096,5.326938,...,6.110919,5.318628,4.045004,1.766740,2.30377,1.71109,1.18857,3.94932,1.05444,..

In [14]:
df_pib2 = df_pib.melt(['Country Name','Country Code'])
df_pib2.head()

  Country Name Country Code variable    value
0    ARGENTINA          ARG     1993  8.20698
1       BELICE          BLZ     1993  6.27569
2      BOLIVIA          BOL     1993  4.26929
3       BRASIL          BRA     1993  4.66517
4        CHILE          CHL     1993  6.58878

In [15]:
df_pib2.rename(columns={'variable':'year',
                        'value': 'PIB'}, inplace=True)


df_pib2.head()

  Country Name Country Code  year      PIB
0    ARGENTINA          ARG  1993  8.20698
1       BELICE          BLZ  1993  6.27569
2      BOLIVIA          BOL  1993  4.26929
3       BRASIL          BRA  1993  4.66517
4        CHILE          CHL  1993  6.58878

AttributeError: 'NoneType' object has no attribute 'head'